FROM python:3.11-slim
WORKDIR /locust

RUN pip install --no-cache-dir locust==2.31.1

COPY ./locust/locustfile.py .

EXPOSE 8089 5557 5558
ENV LOCUST_MODE=master

CMD ["locust", "-f", "locustfile.py", "--master", "--web-port", "8089"]
