FROM eclipse-temurin:21-jdk AS build
WORKDIR /build
COPY . .
RUN ./gradlew :app:fatJar --no-daemon

FROM eclipse-temurin:21-jdk
WORKDIR /app

ENV JAVA_OPTS="-Xms1g -Xmx4g -XX:+UseG1GC -Dfile.encoding=UTF-8"

COPY --from=build /build/app/build/libs/app.jar app.jar
EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
