/*
 * This source file was generated by the Gradle 'init' task
 */
package org.handler;

import org.junit.Test;
import static org.junit.Assert.*;

public class ReverseProxyTest {
    @Test public void appHasAGreeting() {
        ReverseProxy classUnderTest = new ReverseProxy(8080);
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
